module.exports = {
	volumeUp : require('./volumeUp.js'),
	volumeDown : require('./volumeDown.js'),
	stop : require('./stop.js'),
	mediaControl : require('./mediaControl'),
	setMute : require('./setMute'),
	getAudioStatus : require('./getAudioStatus'),
	launchApp : require('./launchApp'),
	getAppStatus : require('./getAppStatus'),
	notification : require('./notification'),
	openChannel : require('./openChannel'),
	getServiceList : require('./getServiceList'),
	getSoftwareInformation : require('./getSoftwareInformation'),
	start : require('./start.js'),
};