module.exports = {
	volumeUp : require('./lib/volumeUp.js'),
	volumeDown : require('./lib/volumeDown.js'),
	stop : require('./lib/stop.js'),
	mediaControl : require('./lib/mediaControl'),
	setMute : require('./lib/setMute'),
	getAudioStatus : require('./lib/getAudioStatus'),
	launchApp : require('./lib/launchApp'),
	getAppStatus : require('./lib/getAppStatus'),
	notification : require('./lib/notification'),
	openChannel : require('./lib/openChannel'),
	getServiceList : require('./lib/getServiceList'),
	getSoftwareInformation : require('./lib/getSoftwareInformation'),
	start : require('./lib/start.js'),
};