module.exports = {
	volumeUp : require('./volumeUp.js'),
	volumeDown : require('./volumeDown.js'),
	switchState: require('./switchState'),
	pause : require('./mediaControl'),
	play : require('./mediaControl'),
	stop : require('./mediaControl'),
	rewind : require('./mediaControl'),
	fastForward : require('./mediaControl'),
	setMuted : require('./setMute'),
	getSources : require('./getSources'),
	openSource : require('./openSource'),
	pressKey : require('./pressKey'),
	setChannel : require('./openChannel'),
	getAudioStatus : require('./getAudioStatus'),
	launchApp : require('./launchApp'),
	getAppStatus : require('./getAppStatus'),
	notification : require('./notification'),
	getServiceList : require('./getServiceList'),
	getSoftwareInformation : require('./getSoftwareInformation'),
	redButton : require('./redButton'),
	greenButton : require('./greenButton'),
	yellowButton : require('./yellowButton'),
	blueButton : require('./blueButton'),
	programMinus : require('./programMinus'),
	programPlus : require('./programPlus'),
	getAppId : require('./getAppId'),
};
